### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by Maxmudjon** [chaeplin/homebridge-mqtt-nest-thermostat#1]
on ESP8266 ?
set payload ?
get payload ?

**Comment by Maxmudjon** [comment]
how to use

**Comment by Maxmudjon** [comment]
I have a ESP8266. it sends the data on the thermometer but the iPhone does not show

**Comment by Maxmudjon** [comment]
on what topic should leave the temperature data

**Comment by chaeplin** [comment]
Well this one works not alone.
I use nest bridge python and use esp8266 to monitor nest hot/cold.
https://github.com/chaeplin/nest-in-korea/tree/master/nest-bridge
https://github.com/chaeplin/esp8266_and_arduino/blob/master/_71-nest-bridgetest/_71-nest-bridgetest.ino
